# This is a basic workflow that is manually triggered

name: Disallow any merging to master if this is not coming from develop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'develop' && github.head_ref.contains('hot_fix_') == false
        run: |
            echo "ERROR: You can only merge to main branch from develop branch or a hot_fix_ branch."
            exit 1
