# This is a basic workflow that is manually triggered

name: 'Disallow any merging to master if this is not coming from develop'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: search_hot_fix
        shell: bash
        run: echo "contains_hot_fix=1" >> $GITHUB_OUTPUT
# for this PR set the contains_hot_fix to zero and then update it
# only if the branch starts with hto_fix_
            # echo "contains_hot_fix=0" >> $GITHUB_OUTPUT
            #if [[$github.head_ref == "hot_fix_"* ]]; then
            #    echo "contains_hot_fix=1" >> $GITHUB_OUTPUT
            #fi

      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'develop' && steps.search_hot_fix.outputs.contains_hot_fix == 0
        run: |
            echo "ERROR: You can only merge to main branch from develop branch or a hot_fix_ branch."
            exit 1
