# This workflow merges a hotfix_ branch into dev
# when the branch is a hotfix_. A hotfix_ branch branches
# from main so we may forget to merge it back into dev

name: merge-hotfix-branch

on:
  pull_request:
    branches: [ master ]
    types: [closed]

# for this PR set the variable contains_hot_fix to zero and then update it
# only if the branch starts with hotfix_

jobs:
  check-branch:
    name: check-hotfix-branch
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - id: search_hotfix
     - name: Extract branch name
       shell: bash
       run: |
           echo "contains_hotfix=0" >> $GITHUB_OUTPUT
           if [[ $GITHUB_HEAD_REF == *"hotfix_"* ]]; then
                echo "contains_hotfix=1" >> $GITHUB_OUTPUT
           fi
     - name: Message System Hot Fix
       if: steps.search_hotfix.outputs.contains_hotfix == 1 
       run: echo "Branch name contains hotfix_."
     - name: Fail hotfix job
       if: github.base_ref == 'master' && github.head_ref != 'develop' && steps.search_hotfix.outputs.contains_hotfix == 0
       run: |
            echo "ERROR: You can only merge to main branch from develop branch or a hotfix_ branch."
            exit 1
  merge-master-to-dev:
     name: merge-master-to-dev-branch
     runs-on: ubuntu-latest
     needs: check-branch
     steps:
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.merge_commit_sha }}
	   fetch-depth: '0'
       - name: Merge master to develop
         if: github.event.pull_request.merged == true
         run: |
          git config --global user.email "a.giavaras@gmail.com"
          git config --global user.name "pockerman"
          git pull origin master
          git fetch
          git checkout develop
          git merge --no-ff origin/master -m "Auto-merge master back to dev"
          git push origin develop
  bump-version-and-push-tag:
   name: bump-version-and-push-tag
   runs-on: ubuntu-latest
   needs: [check-branch, merge-master-to-dev] 
   steps:
     - uses: anothrNick/github-tag-action@v1
       env:
         GITHUB_TOKEN: ${{ secrets.MERGE_HOT_FIX_SECRET }}
         WITH_V: true
         PRERELEASE: false
  echo-success:
   name: echo-success
   needs: [check-branch, merge-master-to-dev, bump-version-and-push-tag]
   steps:
     shell: bash
     run: echo "Successfully merged hotfix, merge main branch into dev and created tag"
   
        
