# This workflow merges a hotfix_ branch into dev
# when the branch is a hotfix_. A hotfix_ branch branches
# from main so we may forget to merge it back into dev

name: merge-hotfix-branch

on:
  pull_request:
    branches: [ master ]
    types: [closed]

# for this PR set the variable contains_hot_fix to zero and then update it
# only if the branch starts with hotfix_

jobs:
  merge-master-to-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
      - name: Extract branch name
        id: search_hot_fix
        shell: bash
        run: | 
            echo "contains_hot_fix=0" >> $GITHUB_OUTPUT

            if [[ $GITHUB_HEAD_REF == *"hotfix_"* ]]; then
                echo "contains_hot_fix=1" >> $GITHUB_OUTPUT
            fi
      - name: Message System Hot Fix
        if: steps.search_hot_fix.outputs.contains_hot_fix == 1
        run: echo "Branch name contains hotfix_."
      - name: Message System Not Hot Fix
        if: steps.search_hot_fix.outputs.contains_hot_fix == 0
        run: echo "Branch name does not contain hotfix_." 
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'develop' && steps.search_hot_fix.outputs.contains_hot_fix == 0
        run: |
            echo "ERROR: You can only merge to main branch from develop branch or a hotfix_ branch."
            exit 1
      - name: Merge master -> develop
        if: github.event.pull_request.merged == true
        run: |
          git config --global user.email "a.giavaras@gmail.com"
          git config --global user.name "pockerman"
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
     - name: Bump version and push tag
       uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
       env:
        WITH_V: true
        PRERELEASE: false

        
