# merges the master branch after a hotfix branch
# has been merged into the master branch and then
# creates a tag
name: merge-hotfix-branch
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  check-branch:
    name: check-hotfix-branch
    runs-on: ubuntu-latest
   
    steps:
      - name: Check branch name
      - uses: actions/checkout@v4
      
          
      
